"""
db_manager.py — SQLite Database Manager
=========================================
Network Traffic Analysis and Intrusion Detection System

Provides a thread-safe, OOP-based SQLite connection manager that handles:
  - Database initialisation and schema creation
  - Connection lifecycle management (context manager support)
  - Traffic packet records table
  - Alerts table
  - Session statistics table
  - Model metadata table (for future ML integration)
  - CRUD helper methods
  - Auto-pruning of stale records

Usage:
    from database.db_manager import DatabaseManager

    db = DatabaseManager()
    db.initialise()

    # Insert a traffic record
    db.insert_traffic_record(record_dict)

    # Fetch recent alerts
    alerts = db.fetch_alerts(limit=50)

    # Use as a context manager
    with DatabaseManager() as db:
        db.execute("SELECT COUNT(*) FROM traffic_records")

Author: Network Traffic Analyzer Project
Version: 1.0.0
Python: 3.11+
"""

from __future__ import annotations

import sqlite3
import threading
from contextlib import contextmanager
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Generator, Optional

from utils.config import config
from utils.logger import get_db_logger

# Module-level logger
log = get_db_logger()


# ──────────────────────────────────────────────────────────────────────────────
# DATA MODELS (Dataclasses)
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class TrafficRecord:
    """
    Represents a single captured network packet / flow record.

    Fields map 1-to-1 with the ``traffic_records`` table columns.
    Optional fields default to None and are filled in by the capture layer.
    """
    timestamp: str                            # ISO-8601 capture timestamp
    src_ip: str                               # Source IP address
    dst_ip: str                               # Destination IP address
    src_port: int                             # Source port (0 if N/A)
    dst_port: int                             # Destination port
    protocol: str                             # Protocol name (TCP/UDP/ICMP…)
    protocol_num: int                         # Protocol number
    packet_length: int                        # Total packet size in bytes
    payload_length: int                       # Payload size in bytes
    ttl: Optional[int] = None                 # Time-To-Live value
    tcp_flags: Optional[str] = None          # TCP flags as hex string
    window_size: Optional[int] = None        # TCP window size
    icmp_type: Optional[int] = None          # ICMP message type
    dns_query: Optional[str] = None          # DNS query name (if applicable)
    http_method: Optional[str] = None        # HTTP method (if applicable)
    http_host: Optional[str] = None          # HTTP host header (if applicable)
    session_id: Optional[str] = None         # Capture session identifier
    label: str = "UNKNOWN"                   # Ground-truth or predicted label
    anomaly_score: Optional[float] = None    # ML anomaly score (Phase 2)
    id: Optional[int] = None                 # Auto-assigned DB primary key


@dataclass
class AlertRecord:
    """
    Represents a security alert generated by a detector or ML model.

    Alerts are stored in the ``alerts`` table and surfaced on the dashboard.
    """
    timestamp: str                            # ISO-8601 alert timestamp
    alert_type: str                           # e.g. "DDoS", "PortScan"
    severity: str                             # "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
    src_ip: str                               # Offending source IP
    dst_ip: str                               # Target IP
    dst_port: Optional[int] = None           # Target port (if applicable)
    protocol: Optional[str] = None           # Associated protocol
    description: str = ""                     # Human-readable alert description
    raw_evidence: Optional[str] = None       # JSON-serialised evidence blob
    is_acknowledged: bool = False            # Analyst acknowledgement flag
    acknowledged_at: Optional[str] = None   # ISO-8601 acknowledgement timestamp
    session_id: Optional[str] = None         # Associated capture session
    id: Optional[int] = None                 # Auto-assigned DB primary key


@dataclass
class SessionRecord:
    """
    Represents a single packet-capture session with aggregate statistics.
    """
    session_id: str                           # UUID for the session
    start_time: str                           # ISO-8601 session start
    end_time: Optional[str] = None           # ISO-8601 session end (None if live)
    interface: str = "unknown"               # Network interface used
    total_packets: int = 0                   # Total packets captured
    total_bytes: int = 0                     # Total bytes captured
    total_alerts: int = 0                    # Alerts raised in session
    pcap_file: Optional[str] = None         # Path to saved PCAP file
    notes: Optional[str] = None             # Analyst notes
    id: Optional[int] = None


@dataclass
class ModelMetadata:
    """
    Stores metadata for trained ML models (used in Phase 2).

    Enables the system to track model versions, performance metrics,
    and which model is currently active.
    """
    model_name: str                           # e.g. "IsolationForest_v1"
    model_type: str                           # e.g. "anomaly_detection"
    model_path: str                           # Absolute path to serialised model
    trained_at: str                           # ISO-8601 training timestamp
    accuracy: Optional[float] = None
    f1_score: Optional[float] = None
    precision: Optional[float] = None
    recall: Optional[float] = None
    training_samples: Optional[int] = None
    feature_names: Optional[str] = None      # JSON list of feature names
    is_active: bool = False                  # Currently deployed model flag
    notes: Optional[str] = None
    id: Optional[int] = None


# ──────────────────────────────────────────────────────────────────────────────
# DATABASE MANAGER
# ──────────────────────────────────────────────────────────────────────────────

class DatabaseManager:
    """
    Thread-safe SQLite database manager for the Network Traffic IDS.

    Provides:
    - Automatic schema creation and migration hooks
    - Context manager support for safe connection handling
    - Typed CRUD operations for each domain entity
    - Connection pooling via per-thread connections
    - Configurable PRAGMA tuning for performance

    Attributes:
        db_path (Path):  Absolute path to the SQLite database file.
        _local (threading.local): Thread-local storage for connections.

    Example:
        # Module-level singleton pattern
        db = DatabaseManager()
        db.initialise()

        # Insert a record
        record = TrafficRecord(timestamp=..., src_ip="10.0.0.1", ...)
        db.insert_traffic_record(record)

        # Context manager pattern
        with DatabaseManager() as manager:
            rows = manager.fetch_recent_traffic(limit=100)
    """

    def __init__(self, db_path: Optional[Path] = None) -> None:
        """
        Initialise the DatabaseManager.

        Args:
            db_path: Path to the SQLite file. Defaults to the path configured
                     in ``config.paths.database_path``.
        """
        self.db_path: Path = db_path or config.paths.database_path
        self._local: threading.local = threading.local()
        self._db_config = config.database

        log.debug("DatabaseManager created. DB path: %s", self.db_path)

    # ── Context Manager Protocol ───────────────────────────────────────────────

    def __enter__(self) -> "DatabaseManager":
        """Open a connection on entry."""
        self._get_connection()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> bool:
        """Close the connection on exit, rolling back on exception."""
        conn = getattr(self._local, "connection", None)
        if conn:
            if exc_type is not None:
                conn.rollback()
                log.warning(
                    "Transaction rolled back due to exception: %s", exc_val
                )
            conn.close()
            self._local.connection = None
        return False   # Re-raise any exception

    # ── Connection Management ──────────────────────────────────────────────────

    def _get_connection(self) -> sqlite3.Connection:
        """
        Return the thread-local SQLite connection, creating one if needed.

        Each thread owns exactly one connection, ensuring thread safety
        without the overhead of a full connection pool.

        Returns:
            An open :class:`sqlite3.Connection`.

        Raises:
            sqlite3.Error: If the connection cannot be established.
        """
        if not hasattr(self._local, "connection") or self._local.connection is None:
            self.db_path.parent.mkdir(parents=True, exist_ok=True)
            try:
                conn = sqlite3.connect(
                    database=str(self.db_path),
                    timeout=self._db_config.timeout,
                    detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES,
                    check_same_thread=False,
                )
                conn.row_factory = sqlite3.Row   # Enable dict-like row access
                self._apply_pragmas(conn)
                self._local.connection = conn
                log.debug("New SQLite connection opened (thread: %s).", threading.get_ident())
            except sqlite3.Error as exc:
                log.error("Failed to open database connection: %s", exc)
                raise

        return self._local.connection

    def _apply_pragmas(self, conn: sqlite3.Connection) -> None:
        """
        Apply performance and integrity PRAGMAs to a new connection.

        Args:
            conn: The SQLite connection to configure.
        """
        pragmas = [
            f"PRAGMA journal_mode = {self._db_config.journal_mode};",
            f"PRAGMA synchronous = {self._db_config.synchronous};",
            f"PRAGMA cache_size = {self._db_config.cache_size};",
            f"PRAGMA foreign_keys = {'ON' if self._db_config.foreign_keys else 'OFF'};",
            "PRAGMA temp_store = MEMORY;",
        ]
        cursor = conn.cursor()
        for pragma in pragmas:
            cursor.execute(pragma)
        conn.commit()
        log.debug("SQLite PRAGMAs applied.")

    @contextmanager
    def _transaction(self) -> Generator[sqlite3.Cursor, None, None]:
        """
        Context manager that yields a cursor within an atomic transaction.

        Commits on success; rolls back and re-raises on any exception.

        Yields:
            sqlite3.Cursor: Ready-to-use database cursor.

        Raises:
            sqlite3.Error: On any database error (after rolling back).
        """
        conn = self._get_connection()
        cursor = conn.cursor()
        try:
            yield cursor
            conn.commit()
        except sqlite3.Error as exc:
            conn.rollback()
            log.error("Database transaction failed: %s", exc)
            raise

    def close(self) -> None:
        """Close the thread-local connection if open."""
        conn = getattr(self._local, "connection", None)
        if conn:
            conn.close()
            self._local.connection = None
            log.debug("SQLite connection closed (thread: %s).", threading.get_ident())

    # ── Schema Initialisation ─────────────────────────────────────────────────

    def initialise(self) -> None:
        """
        Initialise the database by creating all tables (if not already present).

        This is idempotent — safe to call on every application startup.

        Raises:
            sqlite3.Error: If schema creation fails.
        """
        log.info("Initialising database at: %s", self.db_path)
        self._create_traffic_table()
        self._create_alerts_table()
        self._create_sessions_table()
        self._create_model_metadata_table()
        self._create_indexes()
        log.info("Database initialisation complete.")

    def _create_traffic_table(self) -> None:
        """Create the ``traffic_records`` table."""
        ddl = """
        CREATE TABLE IF NOT EXISTS traffic_records (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp       TEXT    NOT NULL,
            src_ip          TEXT    NOT NULL,
            dst_ip          TEXT    NOT NULL,
            src_port        INTEGER NOT NULL DEFAULT 0,
            dst_port        INTEGER NOT NULL DEFAULT 0,
            protocol        TEXT    NOT NULL DEFAULT 'UNKNOWN',
            protocol_num    INTEGER NOT NULL DEFAULT 0,
            packet_length   INTEGER NOT NULL DEFAULT 0,
            payload_length  INTEGER NOT NULL DEFAULT 0,
            ttl             INTEGER,
            tcp_flags       TEXT,
            window_size     INTEGER,
            icmp_type       INTEGER,
            dns_query       TEXT,
            http_method     TEXT,
            http_host       TEXT,
            session_id      TEXT
                REFERENCES capture_sessions(session_id)
                ON DELETE SET NULL,
            label           TEXT    NOT NULL DEFAULT 'UNKNOWN',
            anomaly_score   REAL,
            created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
        );
        """
        with self._transaction() as cursor:
            cursor.execute(ddl)
        log.debug("Table 'traffic_records' ensured.")

    def _create_alerts_table(self) -> None:
        """Create the ``alerts`` table."""
        ddl = """
        CREATE TABLE IF NOT EXISTS alerts (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp           TEXT    NOT NULL,
            alert_type          TEXT    NOT NULL,
            severity            TEXT    NOT NULL DEFAULT 'MEDIUM',
            src_ip              TEXT    NOT NULL,
            dst_ip              TEXT    NOT NULL,
            dst_port            INTEGER,
            protocol            TEXT,
            description         TEXT    NOT NULL DEFAULT '',
            raw_evidence        TEXT,
            is_acknowledged     INTEGER NOT NULL DEFAULT 0,
            acknowledged_at     TEXT,
            session_id          TEXT
                REFERENCES capture_sessions(session_id)
                ON DELETE SET NULL,
            created_at          TEXT    NOT NULL DEFAULT (datetime('now'))
        );
        """
        with self._transaction() as cursor:
            cursor.execute(ddl)
        log.debug("Table 'alerts' ensured.")

    def _create_sessions_table(self) -> None:
        """Create the ``capture_sessions`` table."""
        ddl = """
        CREATE TABLE IF NOT EXISTS capture_sessions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id      TEXT    NOT NULL UNIQUE,
            start_time      TEXT    NOT NULL,
            end_time        TEXT,
            interface       TEXT    NOT NULL DEFAULT 'unknown',
            total_packets   INTEGER NOT NULL DEFAULT 0,
            total_bytes     INTEGER NOT NULL DEFAULT 0,
            total_alerts    INTEGER NOT NULL DEFAULT 0,
            pcap_file       TEXT,
            notes           TEXT,
            created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
        );
        """
        with self._transaction() as cursor:
            cursor.execute(ddl)
        log.debug("Table 'capture_sessions' ensured.")

    def _create_model_metadata_table(self) -> None:
        """Create the ``model_metadata`` table for Phase 2 ML tracking."""
        ddl = """
        CREATE TABLE IF NOT EXISTS model_metadata (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            model_name          TEXT    NOT NULL,
            model_type          TEXT    NOT NULL,
            model_path          TEXT    NOT NULL,
            trained_at          TEXT    NOT NULL,
            accuracy            REAL,
            f1_score            REAL,
            precision_score     REAL,
            recall_score        REAL,
            training_samples    INTEGER,
            feature_names       TEXT,
            is_active           INTEGER NOT NULL DEFAULT 0,
            notes               TEXT,
            created_at          TEXT    NOT NULL DEFAULT (datetime('now'))
        );
        """
        with self._transaction() as cursor:
            cursor.execute(ddl)
        log.debug("Table 'model_metadata' ensured.")

    def _create_indexes(self) -> None:
        """Create performance indexes on high-cardinality query columns."""
        indexes = [
            # traffic_records indexes
            "CREATE INDEX IF NOT EXISTS idx_traffic_timestamp  ON traffic_records(timestamp);",
            "CREATE INDEX IF NOT EXISTS idx_traffic_src_ip     ON traffic_records(src_ip);",
            "CREATE INDEX IF NOT EXISTS idx_traffic_dst_ip     ON traffic_records(dst_ip);",
            "CREATE INDEX IF NOT EXISTS idx_traffic_protocol   ON traffic_records(protocol);",
            "CREATE INDEX IF NOT EXISTS idx_traffic_session    ON traffic_records(session_id);",
            "CREATE INDEX IF NOT EXISTS idx_traffic_label      ON traffic_records(label);",
            # alerts indexes
            "CREATE INDEX IF NOT EXISTS idx_alerts_timestamp   ON alerts(timestamp);",
            "CREATE INDEX IF NOT EXISTS idx_alerts_type        ON alerts(alert_type);",
            "CREATE INDEX IF NOT EXISTS idx_alerts_severity    ON alerts(severity);",
            "CREATE INDEX IF NOT EXISTS idx_alerts_src_ip      ON alerts(src_ip);",
            "CREATE INDEX IF NOT EXISTS idx_alerts_ack         ON alerts(is_acknowledged);",
            # sessions indexes
            "CREATE INDEX IF NOT EXISTS idx_sessions_start     ON capture_sessions(start_time);",
        ]
        with self._transaction() as cursor:
            for stmt in indexes:
                cursor.execute(stmt)
        log.debug("Database indexes ensured.")

    # ── Traffic Record CRUD ────────────────────────────────────────────────────

    def insert_traffic_record(self, record: TrafficRecord) -> int:
        """
        Insert a single traffic record into the database.

        Args:
            record: A :class:`TrafficRecord` dataclass instance.

        Returns:
            The ``rowid`` (primary key) of the newly inserted row.

        Raises:
            sqlite3.Error: On insertion failure.
        """
        sql = """
        INSERT INTO traffic_records (
            timestamp, src_ip, dst_ip, src_port, dst_port,
            protocol, protocol_num, packet_length, payload_length,
            ttl, tcp_flags, window_size, icmp_type,
            dns_query, http_method, http_host,
            session_id, label, anomaly_score
        ) VALUES (
            :timestamp, :src_ip, :dst_ip, :src_port, :dst_port,
            :protocol, :protocol_num, :packet_length, :payload_length,
            :ttl, :tcp_flags, :window_size, :icmp_type,
            :dns_query, :http_method, :http_host,
            :session_id, :label, :anomaly_score
        );
        """
        data = asdict(record)
        data.pop("id", None)   # Let DB auto-assign
        with self._transaction() as cursor:
            cursor.execute(sql, data)
            row_id: int = cursor.lastrowid  # type: ignore[assignment]
        log.debug("Inserted traffic record id=%d.", row_id)
        return row_id

    def insert_traffic_batch(self, records: list[TrafficRecord]) -> int:
        """
        Bulk-insert a list of traffic records in a single transaction.

        Args:
            records: List of :class:`TrafficRecord` instances.

        Returns:
            Number of rows inserted.

        Raises:
            sqlite3.Error: On batch insertion failure.
        """
        if not records:
            return 0

        sql = """
        INSERT INTO traffic_records (
            timestamp, src_ip, dst_ip, src_port, dst_port,
            protocol, protocol_num, packet_length, payload_length,
            ttl, tcp_flags, window_size, icmp_type,
            dns_query, http_method, http_host,
            session_id, label, anomaly_score
        ) VALUES (
            :timestamp, :src_ip, :dst_ip, :src_port, :dst_port,
            :protocol, :protocol_num, :packet_length, :payload_length,
            :ttl, :tcp_flags, :window_size, :icmp_type,
            :dns_query, :http_method, :http_host,
            :session_id, :label, :anomaly_score
        );
        """
        batch = [
            {k: v for k, v in asdict(r).items() if k != "id"}
            for r in records
        ]
        with self._transaction() as cursor:
            cursor.executemany(sql, batch)
        count = len(records)
        log.info("Batch inserted %d traffic records.", count)
        return count

    def fetch_recent_traffic(
        self,
        limit: int = 100,
        offset: int = 0,
        protocol: Optional[str] = None,
        src_ip: Optional[str] = None,
        label: Optional[str] = None,
    ) -> list[dict[str, Any]]:
        """
        Retrieve recent traffic records with optional filtering.

        Args:
            limit:    Maximum number of rows to return (default 100).
            offset:   Pagination offset (default 0).
            protocol: Filter by protocol name (e.g. "TCP").
            src_ip:   Filter by source IP address.
            label:    Filter by traffic label (e.g. "BENIGN", "DDoS").

        Returns:
            List of row dictionaries (column name → value).
        """
        conditions: list[str] = []
        params: dict[str, Any] = {"limit": limit, "offset": offset}

        if protocol:
            conditions.append("protocol = :protocol")
            params["protocol"] = protocol
        if src_ip:
            conditions.append("source_ip = :src_ip")
            params["src_ip"] = src_ip
        if label:
            conditions.append("label = :label")
            params["label"] = label

        where_clause = ("WHERE " + " AND ".join(conditions)) if conditions else ""

        sql = f"""
        SELECT * FROM traffic_logs
        {where_clause}
        ORDER BY timestamp DESC
        LIMIT :limit OFFSET :offset;
        """
        conn = self._get_connection()
        cursor = conn.execute(sql, params)
        rows = [dict(row) for row in cursor.fetchall()]
        log.debug("Fetched %d traffic records.", len(rows))
        return rows

    def get_traffic_count(self) -> int:
        """Return the total number of traffic records in the database."""
        conn = self._get_connection()
        cursor = conn.execute("SELECT COUNT(*) FROM traffic_logs;")
        count: int = cursor.fetchone()[0]
        return count

    # ── Alert CRUD ─────────────────────────────────────────────────────────────

    def insert_alert(self, alert: AlertRecord) -> int:
        """
        Insert a new security alert.

        Args:
            alert: An :class:`AlertRecord` dataclass instance.

        Returns:
            The primary key of the newly created alert row.
        """
        sql = """
        INSERT INTO alerts (
            timestamp, alert_type, severity, src_ip, dst_ip,
            dst_port, protocol, description, raw_evidence,
            is_acknowledged, acknowledged_at, session_id
        ) VALUES (
            :timestamp, :alert_type, :severity, :src_ip, :dst_ip,
            :dst_port, :protocol, :description, :raw_evidence,
            :is_acknowledged, :acknowledged_at, :session_id
        );
        """
        data = asdict(alert)
        data.pop("id", None)
        data["is_acknowledged"] = int(data["is_acknowledged"])
        with self._transaction() as cursor:
            cursor.execute(sql, data)
            row_id: int = cursor.lastrowid  # type: ignore[assignment]
        log.warning(
            "Alert inserted [%s | %s]: %s",
            alert.severity,
            alert.alert_type,
            alert.description[:80],
        )
        return row_id

    def fetch_alerts(
        self,
        limit: int = 50,
        severity: Optional[str] = None,
        alert_type: Optional[str] = None,
        unacknowledged_only: bool = False,
    ) -> list[dict[str, Any]]:
        """
        Retrieve security alerts with optional filtering.

        Args:
            limit:               Maximum number of rows to return.
            severity:            Filter by severity level.
            alert_type:          Filter by alert type (e.g. "DDoS").
            unacknowledged_only: If True, only return unacknowledged alerts.

        Returns:
            List of alert row dictionaries.
        """
        conditions: list[str] = []
        params: dict[str, Any] = {"limit": limit}

        if severity:
            conditions.append("severity = :severity")
            params["severity"] = severity
        if alert_type:
            conditions.append("alert_type = :alert_type")
            params["alert_type"] = alert_type
        if unacknowledged_only:
            conditions.append("is_acknowledged = 0")

        where_clause = ("WHERE " + " AND ".join(conditions)) if conditions else ""

        sql = f"""
        SELECT * FROM alerts
        {where_clause}
        ORDER BY timestamp DESC
        LIMIT :limit;
        """
        conn = self._get_connection()
        cursor = conn.execute(sql, params)
        rows = [dict(row) for row in cursor.fetchall()]
        log.debug("Fetched %d alert records.", len(rows))
        return rows

    def acknowledge_alert(self, alert_id: int) -> bool:
        """
        Mark an alert as acknowledged by an analyst.

        Args:
            alert_id: Primary key of the alert to acknowledge.

        Returns:
            True if the alert was updated; False if not found.
        """
        sql = """
        UPDATE alerts
        SET is_acknowledged = 1,
            acknowledged_at = :now
        WHERE id = :alert_id AND is_acknowledged = 0;
        """
        params = {"alert_id": alert_id, "now": datetime.utcnow().isoformat()}
        with self._transaction() as cursor:
            cursor.execute(sql, params)
            updated = cursor.rowcount > 0
        if updated:
            log.info("Alert id=%d acknowledged.", alert_id)
        return updated

    def get_alert_count(self, unacknowledged_only: bool = False) -> int:
        """Return the total number of alerts (optionally unacknowledged only)."""
        if unacknowledged_only:
            sql = "SELECT COUNT(*) FROM alerts WHERE is_acknowledged = 0;"
        else:
            sql = "SELECT COUNT(*) FROM alerts;"
        conn = self._get_connection()
        cursor = conn.execute(sql)
        count: int = cursor.fetchone()[0]
        return count

    # ── Session CRUD ───────────────────────────────────────────────────────────

    def insert_session(self, session: SessionRecord) -> int:
        """
        Create a new capture session record.

        Args:
            session: A :class:`SessionRecord` instance.

        Returns:
            The primary key of the created session.
        """
        sql = """
        INSERT INTO capture_sessions (
            session_id, start_time, end_time, interface,
            total_packets, total_bytes, total_alerts, pcap_file, notes
        ) VALUES (
            :session_id, :start_time, :end_time, :interface,
            :total_packets, :total_bytes, :total_alerts, :pcap_file, :notes
        );
        """
        data = asdict(session)
        data.pop("id", None)
        with self._transaction() as cursor:
            cursor.execute(sql, data)
            row_id: int = cursor.lastrowid  # type: ignore[assignment]
        log.info("Session '%s' created (id=%d).", session.session_id, row_id)
        return row_id

    def update_session_stats(
        self,
        session_id: str,
        *,
        total_packets: Optional[int] = None,
        total_bytes: Optional[int] = None,
        total_alerts: Optional[int] = None,
        end_time: Optional[str] = None,
    ) -> bool:
        """
        Update aggregate statistics for an existing session.

        Args:
            session_id:    The UUID of the session to update.
            total_packets: New packet count (replaces existing).
            total_bytes:   New byte count (replaces existing).
            total_alerts:  New alert count (replaces existing).
            end_time:      ISO-8601 end time (set when session closes).

        Returns:
            True if the record was updated; False if session not found.
        """
        updates: list[str] = []
        params: dict[str, Any] = {"session_id": session_id}

        if total_packets is not None:
            updates.append("total_packets = :total_packets")
            params["total_packets"] = total_packets
        if total_bytes is not None:
            updates.append("total_bytes = :total_bytes")
            params["total_bytes"] = total_bytes
        if total_alerts is not None:
            updates.append("total_alerts = :total_alerts")
            params["total_alerts"] = total_alerts
        if end_time is not None:
            updates.append("end_time = :end_time")
            params["end_time"] = end_time

        if not updates:
            return False

        sql = f"""
        UPDATE capture_sessions
        SET {', '.join(updates)}
        WHERE session_id = :session_id;
        """
        with self._transaction() as cursor:
            cursor.execute(sql, params)
            updated = cursor.rowcount > 0
        return updated

    # ── Maintenance ────────────────────────────────────────────────────────────

    def prune_old_records(self, keep_latest: Optional[int] = None) -> dict[str, int]:
        """
        Remove the oldest traffic records and alerts beyond the configured
        retention limits.

        Args:
            keep_latest: If provided, keep only this many of the most recent
                         traffic records. Otherwise uses the configured maximum.

        Returns:
            Dictionary with counts of deleted rows per table.
        """
        max_traffic = keep_latest or self._db_config.max_traffic_records
        max_alerts = self._db_config.max_alert_records

        deleted: dict[str, int] = {"traffic_records": 0, "alerts": 0}

        traffic_count = self.get_traffic_count()
        if traffic_count > max_traffic:
            excess = traffic_count - max_traffic
            with self._transaction() as cursor:
                cursor.execute(
                    """
                    DELETE FROM traffic_records
                    WHERE id IN (
                        SELECT id FROM traffic_records
                        ORDER BY timestamp ASC
                        LIMIT ?
                    );
                    """,
                    (excess,),
                )
                deleted["traffic_records"] = cursor.rowcount

        alert_count = self.get_alert_count()
        if alert_count > max_alerts:
            excess = alert_count - max_alerts
            with self._transaction() as cursor:
                cursor.execute(
                    """
                    DELETE FROM alerts
                    WHERE id IN (
                        SELECT id FROM alerts
                        ORDER BY timestamp ASC
                        LIMIT ?
                    );
                    """,
                    (excess,),
                )
                deleted["alerts"] = cursor.rowcount

        if any(deleted.values()):
            log.info("Pruned records: %s", deleted)

        return deleted

    # ── Model Metadata CRUD ───────────────────────────────────────────────────

    def insert_model_metadata(self, record: ModelMetadata) -> int:
        """
        Insert ML model metadata into the ``model_metadata`` table.

        Called by :class:`ModelManager` after each training run to persist
        model performance metrics and file paths to the database.

        Args:
            record: A :class:`ModelMetadata` dataclass instance.

        Returns:
            The primary key of the inserted row.

        Raises:
            sqlite3.Error: On insertion failure.
        """
        sql = """
        INSERT INTO model_metadata (
            model_name, model_type, model_path, trained_at,
            accuracy, f1_score, precision_score, recall_score,
            training_samples, feature_names, is_active, notes
        ) VALUES (
            :model_name, :model_type, :model_path, :trained_at,
            :accuracy, :f1_score, :precision, :recall,
            :training_samples, :feature_names, :is_active, :notes
        );
        """
        # ModelMetadata dataclass uses 'precision' and 'recall' field names.
        # SQL table uses 'precision_score' and 'recall_score' columns.
        # We bind them via :precision / :recall aliases in the SQL.
        data = asdict(record)
        data.pop("id", None)
        data["is_active"] = int(data["is_active"])
        # 'precision' and 'recall' keys already match the SQL binding aliases
        with self._transaction() as cursor:
            cursor.execute(sql, data)
            row_id: int = cursor.lastrowid  # type: ignore[assignment]
        log.debug(
            "Model metadata inserted: '%s' (id=%d).",
            record.model_name, row_id,
        )
        return row_id

    def fetch_model_metadata(
        self,
        model_type: Optional[str] = None,
        active_only: bool = False,
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        """
        Retrieve ML model metadata records.

        Args:
            model_type:  Filter by model type (e.g. "anomaly", "classifier").
            active_only: If True, return only active models.
            limit:       Maximum number of rows to return.

        Returns:
            List of row dictionaries.
        """
        conditions: list[str] = []
        params: dict[str, Any] = {"limit": limit}

        if model_type:
            conditions.append("model_type = :model_type")
            params["model_type"] = model_type
        if active_only:
            conditions.append("is_active = 1")

        where_clause = ("WHERE " + " AND ".join(conditions)) if conditions else ""
        sql = f"""
        SELECT * FROM model_metadata
        {where_clause}
        ORDER BY trained_at DESC
        LIMIT :limit;
        """
        conn = self._get_connection()
        cursor = conn.execute(sql, params)
        rows = [dict(row) for row in cursor.fetchall()]
        log.debug("Fetched %d model metadata records.", len(rows))
        return rows


    def health_check(self) -> dict[str, Any]:
        """
        Run a lightweight health-check on the database connection.

        Returns:
            Dictionary with health status details.
        """
        try:
            conn = self._get_connection()
            conn.execute("SELECT 1;")
            traffic_count = self.get_traffic_count()
            alert_count = self.get_alert_count()
            return {
                "status": "healthy",
                "db_path": str(self.db_path),
                "db_exists": self.db_path.exists(),
                "db_size_bytes": self.db_path.stat().st_size if self.db_path.exists() else 0,
                "traffic_records": traffic_count,
                "total_alerts": alert_count,
                "unacknowledged_alerts": self.get_alert_count(unacknowledged_only=True),
            }
        except Exception as exc:
            log.error("Database health check failed: %s", exc)
            return {"status": "unhealthy", "error": str(exc)}

    def __repr__(self) -> str:
        return f"DatabaseManager(db_path='{self.db_path}')"
